### ISSUE TITLE
工程搭建失败 node  5.8.0

### ISSUE THREAD

**Issue by DexSinis** [WittBulter/easyFindNumber#2]
/root/Documents/easyFindNumber/easyFindNumber/app.js:5
const http = require('http')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3

**Comment by WittBulter** [comment]
不支持严格模式的const。是5.8.0吗，这个问题一般处在老版本里面
尝试更新一下:
sudo npm cache clean -f
sudo npm install -g n
sudo n stable

可以参见这个问题:http://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode
